# Generated by Django 3.1.7 on 2021-04-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterpriseapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='Nit',
            field=models.BigIntegerField(null=True),
        ),
    ]
